# Generated by Django 6.0.2 on 2026-02-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_filial_accountant_remove_filial_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='chairman',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
