# Generated by Django 6.0.2 on 2026-02-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_company_chairman_company_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'client'), ('worker', 'worker'), ('admin', 'admin')], default='client', max_length=20),
        ),
    ]
