# Generated by Django 6.0.2 on 2026-02-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='born_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_serial',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AddField(
            model_name='user',
            name='pinfl',
            field=models.CharField(default='', max_length=14),
        ),
    ]
