# Generated by Django 6.0.2 on 2026-02-16 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bumen', '0001_initial'),
        ('users', '0017_remove_filial_accountant_remove_filial_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='client',
        ),
        migrations.RemoveField(
            model_name='documentrequest',
            name='client',
        ),
        migrations.AddField(
            model_name='document',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='users.company'),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.company'),
        ),
    ]
