# Generated by Django 6.0.2 on 2026-02-16 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bumen', '0002_remove_document_client_remove_documentrequest_client_and_more'),
        ('users', '0017_remove_filial_accountant_remove_filial_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
        migrations.AddField(
            model_name='file',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='users.company'),
        ),
        migrations.AlterField(
            model_name='file',
            name='document_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='bumen.documentrequest'),
        ),
    ]
