# Generated by Django 6.0.2 on 2026-02-16 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bumen', '0003_remove_file_user_file_company_and_more'),
        ('users', '0017_remove_filial_accountant_remove_filial_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationrequest',
            name='client',
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='status',
            field=models.CharField(choices=[('signed', 'signed'), ('pending', 'pending'), ('rejected', 'rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.company'),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
