# Generated by Django 6.0.2 on 2026-02-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bumen', '0004_remove_verificationrequest_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='desc',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('signed', 'signed'), ('pending', 'pending'), ('rejected', 'rejected')], default='standard', max_length=20),
        ),
    ]
