# Generated by Django 6.0.2 on 2026-02-18 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bumen', '0009_alter_signature_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='document',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signs', to='bumen.documentrequest'),
        ),
    ]
