# Generated by Django 6.0.2 on 2026-02-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bumen', '0011_alter_signature_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
