# Generated by Django 6.0.2 on 2026-02-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bumen', '0012_documentrequest_end_date_documentrequest_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='signature',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='signature',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='signature',
            name='valid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
