# Generated by Django 6.0.2 on 2026-02-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bumen', '0013_documentrequest_desc_signature_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
