# Generated by Django 6.0.2 on 2026-02-21 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bumen', '0014_alter_signature_start_date'),
        ('users', '0019_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.company'),
        ),
    ]
