# Generated by Django 6.0.2 on 2026-02-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bumen', '0015_signature_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('signed', 'signed'), ('pending', 'pending'), ('rejected', 'rejected'), ('done', 'done')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='status',
            field=models.CharField(choices=[('signed', 'signed'), ('pending', 'pending'), ('rejected', 'rejected'), ('done', 'done')], default='pending', max_length=20),
        ),
    ]
